// <auto-generated />
namespace Collaborate_lrn_Py.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rmboolintutmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rmboolintutmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201607262033556_rm bool in tut model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
