// <auto-generated />
namespace Collaborate_lrn_Py.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class errormessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(errormessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201607280243338_error message "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
