// <auto-generated />
namespace Collaborate_lrn_Py.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class manytomanyrltocollabtutorials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomanyrltocollabtutorials));
        
        string IMigrationMetadata.Id
        {
            get { return "201607181811230_manytomany rl to collabtutorials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
