// <auto-generated />
namespace Collaborate_lrn_Py.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rmQuiz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rmQuiz));
        
        string IMigrationMetadata.Id
        {
            get { return "201607051906419_rmQuiz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
